-- TABLA PARA SABER LOS TIPOS DE NOMINA
CREATE TABLE [dbo].[AN_TIPOS](
	[TIPO_NOM] [varchar](2) NOT NULL,
	[PERIODICIDAD] [varchar](2) NULL,
	[DESC_TIPO_NOM] [varchar](40) NULL,
	[NUM_PER_ACTUAL] [int] NULL,
	[TAB_ISR] [varchar](2) NULL,
	[TAB_SUB_ISR] [varchar](2) NULL,
	[TAB_CRED_ISR] [varchar](2) NULL,
	[TAB_VAC] [varchar](2) NULL,
	[TAB_AGUINALDO] [varchar](2) NULL,
	[TAB_DESGLOSE] [varchar](2) NULL,
	[CLV_CAL_SEMANA] [varchar](2) NULL,
	[DIAS_ELEVAR] [decimal](12, 2) NULL,
	[STATUS] [varchar](1) NULL,
 CONSTRAINT [CONSTAN_TIPOS] PRIMARY KEY NONCLUSTERED 
(
	[TIPO_NOM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

---TABLA DONDE SE GUARDARA LOS CALENDARIOS 
CREATE TABLE [dbo].[AN_CAL_PERIODOS](
	[TIPO_NOM] [varchar](2) NOT NULL,
	[PERIODO_ANUAL] [int] NOT NULL,
	[NUM_PERIODO] [int] NOT NULL,
	[FECHA_DESDE] [varchar](8) NULL,
	[FECHA_HASTA] [varchar](8) NULL,
	[DIAS_PERIODO] [int] NULL,
	[MES_ACUMULADO] [varchar](2) NULL,
	[FECHA_CALCULO] [varchar](8) NULL,
	[FECHA_CIERRE] [varchar](8) NULL,
	[TIPO_PERIODO] [varchar](1) NULL,
	[STATUS] [varchar](1) NULL,
	[AHORRO] [varchar](1) NULL,
	[OTORGA_PRESTAMO] [varchar](1) NULL,
	[DESCUENTA_PRESTAMO] [varchar](1) NULL,
	[PAGAR_PRESTAMO_CAJA] [varchar](1) NULL,
	[LIQUIDAR_AHORRO] [varchar](1) NULL,
	[APORTACION] [decimal](12, 2) NULL,
	[INTERES_PRESTAMO] [decimal](12, 2) NULL,
	[DESCUENTOS_PRESTAMOS] [decimal](12, 2) NULL,
	[DISPOSICION_PRESTAMO] [decimal](12, 2) NULL,
	[INTERESES_INVERSION] [decimal](12, 2) NULL,
	[F_INI_CASIST] [varchar](8) NULL,
	[F_TER_CASIST] [varchar](8) NULL
) ON [PRIMARY]
GO


